#!/bin/bash
#Script to echo out command-line arguments
echo "The first argument is $1, the second is $2."
echo "The command itself is called $0."
echo "Amount of arguments is : $#"
echo "Store all taken arguments: $@"
echo "What it is: $*"
