#!/bin/bash
#Realiza uma ação com base no dia da semana

case `date +%a` in "Mon")
        BACKUP=/home/serra/data0
        TAPE=/dev/rft0
#Note o uso de dois pontos e virgulas  para terminar cada opção
        ;;
#Note o uso de "|" para querer dizer "ou"
        "Tue" | "Thu")
        BACKUP=/home/serra/data1
        TAPE=/dev/rft1
        ;;
        "Wed" | "Fri")
        BACKUP=/home/serra/data2
        TAPE=/dev/rft2
        ;;
# Não faz backups no final de semana.
        *)

       BACKUP="none"
            TAPE=/dev/null
        ;; 
esac
